"""Package version alignment (issue 214).

Owner ruling, effective v2.3.0 onward: the package version is version-leads-tag
-- ``pyproject.toml``'s ``[project].version`` must equal the current release
tag exactly. This is not a one-time fix: every future release PR must bump
``EXPECTED_VERSION`` below (and ``pyproject.toml``, and any other declared
copy the sweep in issue 214 found -- ``app/main.py``'s ``FastAPI(version=...)``
and the pinned ``openapi/openapi.json`` regenerated via
``python scripts/generate_openapi_spec.py``) in lockstep with the new tag. A
release that forgets this file goes red, by design.

Both the on-disk ``pyproject.toml`` declaration and (when trustworthy) the
installed package's ``importlib.metadata`` version are checked. The repo's
``.venv`` installs this package editable via setuptools, whose
``copilot_agent.egg-info/PKG-INFO`` is only regenerated by an explicit
``pip install -e .`` -- it does NOT update automatically when
``pyproject.toml`` is hand-edited. So a version bump here must be paired with
re-running that install command, or ``importlib.metadata`` silently goes
stale relative to the source of truth. This test surfaces that drift instead
of hiding it: it does not compare metadata to a hardcoded expectation
independent of pyproject -- it compares metadata to what pyproject itself
declares, so it fails loudly if the two are ever allowed to disagree.
"""

from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - project requires-python >=3.11
    import tomli as tomllib

EXPECTED_VERSION = "2.3.0"

PYPROJECT_PATH = Path(__file__).resolve().parent.parent / "pyproject.toml"


def _declared_pyproject_version() -> str:
    with PYPROJECT_PATH.open("rb") as fh:
        data = tomllib.load(fh)
    return data["project"]["version"]


def test_pyproject_version_matches_release_tag() -> None:
    assert _declared_pyproject_version() == EXPECTED_VERSION


def test_importlib_metadata_matches_declared_pyproject_version() -> None:
    """Guards against the editable-install staleness described in the module
    docstring: the installed distribution metadata must agree with the
    version declared in ``pyproject.toml``, not just with a hardcoded
    constant, so a forgotten ``pip install -e .`` after a version bump is
    caught here rather than shipping silently mismatched metadata."""
    installed_version = metadata.version("copilot-agent")
    assert installed_version == _declared_pyproject_version()
