"""Guards issue 213's fix: the container build is hash-locked and reproducible.

pyproject.toml's floor/ceiling ranges (#196) describe the human-facing
contract -- what versions are acceptable -- but two builds from the same
commit could still resolve two different (both range-valid) dependency
trees, e.g. picking up a `starlette` release with a fresh CVE the moment
it lands on PyPI, with no signal in the diff. This test does not
re-litigate #196's range policy; it guards that ``requirements.txt``
(generated by ``scripts/lock-deps.sh``) exists, exactly pins every
production dependency with a hash, and stays consistent with the ranges
pyproject.toml still declares.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.version import Version

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - project requires-python >=3.11
    import tomli as tomllib

PYPROJECT_PATH = Path(__file__).resolve().parent.parent / "pyproject.toml"
REQUIREMENTS_PATH = Path(__file__).resolve().parent.parent / "requirements.txt"

_HASH_RE = re.compile(r"--hash=sha256:[0-9a-f]{64}")
# pip-compile's `--generate-hashes` output wraps continuation lines in `\`;
# a "logical requirement" is a `name==version` line plus every backslash-
# continued line that follows it, up to (but not including) the next
# non-continued, non-comment, non-blank line.
_PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([A-Za-z0-9.+!_-]+)")


def _load_runtime_dependency_specs() -> list[tuple[str, str]]:
    """Project-name / raw-specifier pairs for `[project.dependencies]` only.

    Deliberately excludes the `dev` extra -- the lockfile covers the
    production runtime closure (what `pip install --require-hashes` installs
    in the image), not the dev/test toolchain.
    """
    with PYPROJECT_PATH.open("rb") as f:
        data = tomllib.load(f)

    raw_specs: list[str] = list(data["project"]["dependencies"])
    return [(Requirement(raw).name, str(Requirement(raw).specifier)) for raw in raw_specs]


def _load_logical_lines() -> list[str]:
    """Join each requirement's backslash-continued lines into one logical line.

    pip-compile's hash output spreads one requirement across several
    physical lines (`name==version \\`, then one `--hash=...` per
    continuation line). Collapsing them lets the assertions below reason
    about "this requirement's hashes" as a single string.
    """
    text = REQUIREMENTS_PATH.read_text(encoding="utf-8")
    logical_lines: list[str] = []
    current: list[str] = []
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        current.append(raw_line)
        if not raw_line.rstrip().endswith("\\"):
            logical_lines.append("\n".join(current))
            current = []
    assert not current, "requirements.txt ends mid-continuation (dangling trailing backslash)"
    return logical_lines


def test_requirements_lockfile_exists() -> None:
    assert REQUIREMENTS_PATH.exists(), (
        "services/copilot-agent/requirements.txt is missing -- generate it with "
        "scripts/lock-deps.sh (issue 213)."
    )


def _load_pinned_entries() -> list[tuple[str, str]]:
    """(name, version) for every pinned requirement line, in file order.

    Shared by every test below that needs to know what's pinned, so the
    `name==version` parsing lives in exactly one place.
    """
    entries: list[tuple[str, str]] = []
    for line in _load_logical_lines():
        match = _PIN_RE.match(line)
        if match:
            entries.append((Requirement(f"{match.group(1)}=={match.group(2)}").name, match.group(2)))
    return entries


def test_every_runtime_dependency_is_pinned_in_lockfile() -> None:
    specs = _load_runtime_dependency_specs()
    pinned_names = {name for name, _ in _load_pinned_entries()}

    missing = [name for name, _ in specs if name not in pinned_names]
    assert not missing, (
        f"{missing} declared in pyproject.toml's [project.dependencies] but not "
        "exactly pinned (`name==version`) in requirements.txt -- regenerate the "
        "lock with scripts/lock-deps.sh."
    )


def test_every_lockfile_requirement_has_a_hash() -> None:
    logical_lines = _load_logical_lines()
    assert logical_lines, "requirements.txt has no requirement lines to check"

    unhashed = [line.splitlines()[0] for line in logical_lines if not _HASH_RE.search(line)]
    assert not unhashed, (
        f"{unhashed} have no `--hash=sha256:...` entry -- requirements.txt must be "
        "generated with `pip-compile --generate-hashes` (scripts/lock-deps.sh) so "
        "`pip install --require-hashes` can verify every package."
    )


def test_starlette_transitive_is_pinned() -> None:
    """#184's motivating transitive (fastapi's own dependency) must be locked too."""
    starlette_entries = [name for name, _ in _load_pinned_entries() if name == "starlette"]
    assert len(starlette_entries) == 1, (
        "expected exactly one pinned `starlette==` line in requirements.txt "
        f"(found {len(starlette_entries)}) -- fastapi's transitive dependency must "
        "be locked, not left to resolve freely."
    )


def test_lockfile_pins_satisfy_pyproject_ranges() -> None:
    """Every pinned version must still fall inside pyproject's declared range.

    A lockfile that drifts out of the human-facing range (e.g. someone hand-
    edits requirements.txt, or pyproject's ceiling tightens without
    regenerating the lock) would defeat the purpose of keeping both files --
    the lock is supposed to be one concrete point INSIDE the declared range,
    not a replacement for it.
    """
    specs = _load_runtime_dependency_specs()
    pinned_versions = dict(_load_pinned_entries())

    out_of_range = [
        f"{name}=={pinned_versions[name]} does not satisfy pyproject's {specifier}"
        for name, specifier in specs
        if name in pinned_versions
        and not SpecifierSet(specifier).contains(Version(pinned_versions[name]))
    ]
    assert not out_of_range, (
        f"{out_of_range} -- requirements.txt is out of sync with pyproject.toml's "
        "declared ranges; regenerate the lock with scripts/lock-deps.sh."
    )
