"""Hermetic tests for ``app.ingestion`` (P3.1 document ingestion, first
slice: ``doc_type="lab_pdf"``).

Everything here is hermetic: the VLM is a scripted double
(``_FakeVlmOllama``), never a real Ollama call -- mirrors
``tests/test_extraction.py``'s ``_FakeExtractOllama`` pattern. PDF
rendering itself IS real (``pypdfium2`` over the committed fixture,
``tests/fixtures/lab_report_synthetic.pdf``, generated by
``scripts/generate_lab_pdf_fixture.py``) -- it is fast, deterministic, and
needs no model or network.

Pins two contracts:
  1. ``attach_and_extract`` returns schema-valid ``LabResultFact`` objects,
     each carrying a ``Citation`` back to its source page.
  2. The no-fabrication rule: a field the (scripted, standing in for the
     real) VLM could not read comes back ``None``, never a guessed value --
     exercised via the fixture's deliberately redacted field (Creatinine's
     collection date on page 2).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pypdfium2 as pdfium
import pytest

from app.ingestion import (
    MAX_PAGE_POINTS,
    MAX_PAGES,
    ExtractedLabRow,
    IngestionError,
    IngestionResult,
    LabPageExtraction,
    LocalIngestionStore,
    attach_and_extract,
    render_pdf_pages_to_png,
)
from app.ollama_client import OllamaError
from app.schemas.ingestion import DocumentCitation, IntakeFormExtraction, IntakeFormFact, LabFlagCode, LabResultFact
from app.verification import CitationStatus, CorpusChunkIndex, DocumentFactIndex, check_document_citation

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "lab_report_synthetic.pdf"
_INTAKE_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "intake_form_synthetic.pdf"


def _build_pdf(path: Path, page_sizes: list[tuple[float, float]]) -> Path:
    """Build a cheap, valid, blank PDF at ``path`` with one page per entry in
    ``page_sizes`` -- no fpdf2/reportlab needed, pypdfium2 (already a main
    dependency) can author minimal PDFs directly."""
    pdf = pdfium.PdfDocument.new()
    for width, height in page_sizes:
        pdf.new_page(width, height)
    pdf.save(str(path))
    pdf.close()
    return path

# Mirrors scripts/generate_lab_pdf_fixture.py's page content exactly -- the
# scripted double stands in for what a real VLM reading these page images
# would report, including the one deliberately unreadable field (page 2's
# Creatinine collection_date, covered by an opaque box in the fixture).
_PAGE_1_ROWS = [
    ExtractedLabRow(test="Hemoglobin A1c", value="5.4", unit="%", reference_range="4.0-5.6", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="Fasting Glucose", value="142", unit="mg/dL", reference_range="70-99", collection_date="2026-06-01", abnormal_flag="H"),
    ExtractedLabRow(test="Total Cholesterol", value="188", unit="mg/dL", reference_range="<200", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="LDL Cholesterol", value="112", unit="mg/dL", reference_range="<100", collection_date="2026-06-01", abnormal_flag="H"),
]
_PAGE_2_ROWS = [
    ExtractedLabRow(test="HDL Cholesterol", value="58", unit="mg/dL", reference_range="40-60", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="Triglycerides", value="97", unit="mg/dL", reference_range="<150", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="TSH", value="2.1", unit="mIU/L", reference_range="0.4-4.0", collection_date="2026-06-01", abnormal_flag="N"),
    # The deliberately unreadable field: collection_date is None, never guessed.
    ExtractedLabRow(test="Creatinine", value="0.9", unit="mg/dL", reference_range="0.6-1.3", collection_date=None, abnormal_flag="N"),
]


class _FakeVlmOllama:
    """Scripted VLM extraction double: returns one canned extraction result
    per call, in order (or raises), and records what it was called with.
    ``results`` is untyped-element (``LabPageExtraction`` for lab_pdf tests,
    ``IntakeFormExtraction`` for intake_form tests) -- this one double is
    reused for both doc types' tests, standing in for whichever schema the
    real VLM call would be constrained to."""

    def __init__(self, results: list[Any] | None = None, *, error: bool = False) -> None:
        self._results = results or []
        self._error = error
        self.extract_calls: list[tuple[list[dict[str, Any]], type, list[str] | None]] = []

    def extract(
        self, prompt_or_messages: Any, schema: type, *, options: Any = None, images: list[str] | None = None
    ) -> Any:
        self.extract_calls.append((prompt_or_messages, schema, images))
        if self._error:
            raise OllamaError("scripted VLM extraction failure")
        return self._results[len(self.extract_calls) - 1]


@pytest.fixture
def fake_vlm() -> _FakeVlmOllama:
    return _FakeVlmOllama([LabPageExtraction(rows=_PAGE_1_ROWS), LabPageExtraction(rows=_PAGE_2_ROWS)])


@pytest.fixture
def store(tmp_path: Path) -> LocalIngestionStore:
    return LocalIngestionStore(base_dir=tmp_path / "ingestion")


# ---------------------------------------------------------------------------
# 1. PDF page rendering (real pypdfium2, no model call)
# ---------------------------------------------------------------------------


def test_render_pdf_pages_to_png_returns_one_image_per_page():
    pages = render_pdf_pages_to_png(_FIXTURE_PATH)

    assert len(pages) == 2
    for page_png in pages:
        assert page_png.startswith(b"\x89PNG\r\n\x1a\n")  # PNG magic bytes


# ---------------------------------------------------------------------------
# 2. attach_and_extract: schema-valid facts + citations
# ---------------------------------------------------------------------------


def test_attach_and_extract_returns_schema_valid_facts_with_citations(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    assert isinstance(result, IngestionResult)
    assert len(result.facts) == 8  # 4 rows/page x 2 pages
    for fact in result.facts:
        assert isinstance(fact, LabResultFact)
        assert fact.citation.source_type == "lab_pdf"
        assert fact.citation.source_id == result.source_id


def test_attach_and_extract_citations_carry_the_correct_page_number(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    page_1_facts = [f for f in result.facts if f.test == "Hemoglobin A1c"]
    page_2_facts = [f for f in result.facts if f.test == "HDL Cholesterol"]
    assert page_1_facts[0].citation.page_or_section == "page 1"
    assert page_2_facts[0].citation.page_or_section == "page 2"


def test_attach_and_extract_calls_vlm_once_per_page_with_that_pages_image(fake_vlm, store):
    attach_and_extract(1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store)

    assert len(fake_vlm.extract_calls) == 2
    for _messages, schema, images in fake_vlm.extract_calls:
        assert schema is LabPageExtraction
        assert images is not None
        assert len(images) == 1  # one image (this page) per call


# ---------------------------------------------------------------------------
# 2a. Issue #40: a repeat lab panel (same test extracted twice, e.g. across
# two dated draws on different pages) must produce two INDEPENDENTLY citable
# facts, not a collision on (source_id, field_or_chunk_id). Before the fix,
# ``field_or_chunk_id`` was the test name alone, so this scenario either
# silently last-won or (post-P3.6 interim guard) made
# ``DocumentFactIndex.from_citations`` raise -- both wrong: two distinct,
# real facts must each be checkable on their own terms.
# ---------------------------------------------------------------------------


def test_repeat_test_across_pages_gets_distinct_field_or_chunk_ids(store):
    """Same test ("Glucose"), two different pages/dates/values -- the
    ingestion-assembled citations must not collide on
    (source_id, field_or_chunk_id)."""
    page_1_rows = [
        ExtractedLabRow(
            test="Glucose", value="105", unit="mg/dL", reference_range="70-99",
            collection_date="2026-01-01", abnormal_flag="H",
        ),
    ]
    page_2_rows = [
        ExtractedLabRow(
            test="Glucose", value="250", unit="mg/dL", reference_range="70-99",
            collection_date="2026-06-01", abnormal_flag="H",
        ),
    ]
    vlm = _FakeVlmOllama([LabPageExtraction(rows=page_1_rows), LabPageExtraction(rows=page_2_rows)])

    result = attach_and_extract(1, _FIXTURE_PATH, "lab_pdf", ollama_client=vlm, document_store=store, fact_store=store)

    assert len(result.facts) == 2
    first, second = result.facts
    assert first.citation.source_id == second.citation.source_id  # same document
    assert first.citation.field_or_chunk_id != second.citation.field_or_chunk_id

    # Desired end state (P3.6a): both occurrences are independently indexable
    # and citable -- building the RAW fact index from these two real
    # citations must NOT raise (no key collision), and each citation must
    # verify against ITS OWN occurrence's quote, fail-closed against the
    # other's.
    fact_index = DocumentFactIndex.from_citations([first.citation, second.citation])
    corpus_index = CorpusChunkIndex.from_chunks([])

    correct_first = DocumentCitation(
        source_type="lab_pdf",
        source_id=first.citation.source_id,
        page_or_section=first.citation.page_or_section,
        field_or_chunk_id=first.citation.field_or_chunk_id,
        quote_or_value=first.citation.quote_or_value,
    )
    assert check_document_citation(correct_first, fact_index, corpus_index).status is CitationStatus.VALID

    # Fail-closed check: citing the FIRST occurrence's key but asserting the
    # SECOND occurrence's quote must still mismatch -- uniqueness must not
    # weaken the existing wrong-quote detection.
    wrong_quote_for_first_key = DocumentCitation(
        source_type="lab_pdf",
        source_id=first.citation.source_id,
        page_or_section=first.citation.page_or_section,
        field_or_chunk_id=first.citation.field_or_chunk_id,
        quote_or_value=second.citation.quote_or_value,
    )
    assert (
        check_document_citation(wrong_quote_for_first_key, fact_index, corpus_index).status
        is CitationStatus.VALUE_MISMATCH
    )


# P3.2 note: this test previously exercised "intake_form" as the unsupported
# doc_type -- P3.2 implements that slice (see section 9 below), so it is now
# a *supported* value and no longer proves anything about rejection. Updated
# to a genuinely unsupported literal so the test still pins "an unknown
# doc_type raises ValueError", the behavior it was actually written to cover.
def test_attach_and_extract_rejects_unsupported_doc_type(fake_vlm, store):
    with pytest.raises(ValueError, match="unknown_doc_type"):
        attach_and_extract(
            1, _FIXTURE_PATH, "unknown_doc_type", ollama_client=fake_vlm, document_store=store, fact_store=store  # type: ignore[arg-type]
        )


# ---------------------------------------------------------------------------
# 3. No-fabrication: the deliberately unreadable field never gets a guess
# ---------------------------------------------------------------------------


def test_unreadable_field_yields_none_not_a_guessed_value(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    creatinine = next(f for f in result.facts if f.test == "Creatinine")
    assert creatinine.collection_date is None
    # Every other field on the same row was legible and is NOT None -- proves
    # the None is specific to the unreadable field, not a whole-row failure.
    assert creatinine.value == "0.9"
    assert creatinine.unit == "mg/dL"


def test_unreadable_field_citation_quote_reflects_not_found(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    creatinine = next(f for f in result.facts if f.test == "Creatinine")
    # The citation's quote is for the row's headline value (legible: "0.9"),
    # not the missing collection_date -- it must never claim a date was read.
    assert "0.9" in creatinine.citation.quote_or_value
    assert "2026" not in creatinine.citation.quote_or_value


def test_all_none_row_citation_quote_says_not_found():
    from app.ingestion import _quote_for_row

    row = ExtractedLabRow(test="Illegible Test", value=None, unit=None, reference_range=None, collection_date=None, abnormal_flag=None)
    assert _quote_for_row(row, normalized_flag=None) == "Illegible Test: (not found)"


def test_all_pages_failing_yields_no_facts_and_marks_every_page_failed(store):
    failing_vlm = _FakeVlmOllama(error=True)

    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=failing_vlm, document_store=store, fact_store=store
    )

    # Fails soft, but to EMPTY -- never fabricates rows for a page the VLM
    # couldn't process at all -- AND every page is recorded in failed_pages,
    # so this stays distinguishable from "every page legitimately had zero
    # rows" (see IngestionResult.failed_pages's docstring).
    assert result.facts == []
    assert result.failed_pages == [1, 2]
    assert result.pages_total == 2


# ---------------------------------------------------------------------------
# 4. LocalIngestionStore (P3.1's disclosed local-disk storage placeholder)
# ---------------------------------------------------------------------------


def test_local_store_persists_the_source_document_bytes(tmp_path: Path):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")

    source_id = store.save_source_document(1, "lab_pdf", _FIXTURE_PATH)

    saved = tmp_path / "ingestion" / "documents" / f"{source_id}.pdf"
    assert saved.read_bytes() == _FIXTURE_PATH.read_bytes()


def test_local_store_persists_facts_as_json(tmp_path: Path, fake_vlm):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")

    result = attach_and_extract(
        42, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    saved = tmp_path / "ingestion" / "facts" / f"{result.source_id}.json"
    payload = json.loads(saved.read_text())
    assert payload["patient_id"] == 42
    assert payload["source_id"] == result.source_id
    assert len(payload["facts"]) == 8
    assert payload["facts"][0]["citation"]["source_type"] == "lab_pdf"


def test_local_store_generates_distinct_source_ids(tmp_path: Path):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")

    first = store.save_source_document(1, "lab_pdf", _FIXTURE_PATH)
    second = store.save_source_document(1, "lab_pdf", _FIXTURE_PATH)

    assert first != second


# ---------------------------------------------------------------------------
# 5. Security gate: bounded PDF rendering (DoS) -- MAX_PAGES / MAX_PAGE_POINTS
# ---------------------------------------------------------------------------


def test_render_rejects_a_pdf_exceeding_max_pages(tmp_path: Path):
    oversized = _build_pdf(tmp_path / "many_pages.pdf", [(200.0, 200.0)] * (MAX_PAGES + 1))

    with pytest.raises(IngestionError, match=str(MAX_PAGES)):
        render_pdf_pages_to_png(oversized)


def test_render_accepts_a_pdf_at_exactly_max_pages(tmp_path: Path):
    at_limit = _build_pdf(tmp_path / "at_limit.pdf", [(200.0, 200.0)] * MAX_PAGES)

    pages = render_pdf_pages_to_png(at_limit)

    assert len(pages) == MAX_PAGES


def test_render_rejects_an_oversized_page_dimension(tmp_path: Path):
    huge = _build_pdf(tmp_path / "huge_page.pdf", [(MAX_PAGE_POINTS + 1, 200.0)])

    with pytest.raises(IngestionError, match="exceeds"):
        render_pdf_pages_to_png(huge)


def test_render_accepts_a_page_at_exactly_the_dimension_limit(tmp_path: Path):
    at_limit = _build_pdf(tmp_path / "at_dimension_limit.pdf", [(MAX_PAGE_POINTS, 200.0)])

    pages = render_pdf_pages_to_png(at_limit)

    assert len(pages) == 1


# ---------------------------------------------------------------------------
# 6. Security gate: validate-then-store -- no orphaned state on parse failure
# ---------------------------------------------------------------------------


def test_render_rejects_malformed_bytes_with_a_typed_error(tmp_path: Path):
    malformed = tmp_path / "malformed.pdf"
    malformed.write_bytes(b"this is not a pdf")

    with pytest.raises(IngestionError):
        render_pdf_pages_to_png(malformed)


def test_attach_and_extract_rejects_malformed_pdf_and_stores_nothing(tmp_path: Path, fake_vlm):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")
    malformed = tmp_path / "malformed.pdf"
    malformed.write_bytes(b"this is not a pdf")

    with pytest.raises(IngestionError):
        attach_and_extract(1, malformed, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store)

    assert list((tmp_path / "ingestion" / "documents").iterdir()) == []
    assert list((tmp_path / "ingestion" / "facts").iterdir()) == []


def test_attach_and_extract_rejects_too_many_pages_and_stores_nothing(tmp_path: Path, fake_vlm):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")
    oversized = _build_pdf(tmp_path / "many_pages.pdf", [(200.0, 200.0)] * (MAX_PAGES + 1))

    with pytest.raises(IngestionError):
        attach_and_extract(1, oversized, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store)

    assert list((tmp_path / "ingestion" / "documents").iterdir()) == []
    assert list((tmp_path / "ingestion" / "facts").iterdir()) == []
    assert fake_vlm.extract_calls == []  # never even reached the VLM call


# ---------------------------------------------------------------------------
# 7. Code-review gate: failed-page visibility (IngestionResult.failed_pages)
# ---------------------------------------------------------------------------


def test_mixed_outcome_keeps_succeeded_page_facts_and_marks_only_the_failed_page(store):
    class _MixedVlm:
        """Page 1 succeeds, page 2 fails outright."""

        def __init__(self) -> None:
            self.calls = 0

        def extract(self, prompt_or_messages: Any, schema: type, *, options: Any = None, images: list[str] | None = None) -> Any:
            self.calls += 1
            if self.calls == 1:
                return LabPageExtraction(rows=_PAGE_1_ROWS)
            raise OllamaError("scripted failure on page 2")

    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=_MixedVlm(), document_store=store, fact_store=store
    )

    assert [f.test for f in result.facts] == [row.test for row in _PAGE_1_ROWS]
    assert result.failed_pages == [2]
    assert result.pages_total == 2


# ---------------------------------------------------------------------------
# 8. Code-review gate: page-level flag-code tolerance (LabFlagCode)
# ---------------------------------------------------------------------------


def test_lowercase_flag_code_normalizes_to_the_enum(store):
    lowercase_row = ExtractedLabRow(
        test="Sodium",
        value="140",
        unit="mmol/L",
        reference_range="136-145",
        collection_date="2026-06-01",
        abnormal_flag="h",
    )
    vlm = _FakeVlmOllama([LabPageExtraction(rows=[lowercase_row]), LabPageExtraction(rows=[])])

    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=vlm, document_store=store, fact_store=store
    )

    sodium = next(f for f in result.facts if f.test == "Sodium")
    assert sodium.abnormal_flag == LabFlagCode.HIGH


def test_unrecognized_flag_code_keeps_the_row_but_nulls_the_flag_and_quotes_it(store):
    unknown_row = ExtractedLabRow(
        test="Potassium",
        value="4.1",
        unit="mmol/L",
        reference_range="3.5-5.0",
        collection_date="2026-06-01",
        abnormal_flag="XX",
    )
    vlm = _FakeVlmOllama([LabPageExtraction(rows=[unknown_row]), LabPageExtraction(rows=[])])

    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=vlm, document_store=store, fact_store=store
    )

    # The row is KEPT -- the whole page is NOT dropped over one bad code --
    # just with a null flag; the citation quotes the raw code truthfully
    # rather than silently discarding what the page actually printed.
    potassium = next(f for f in result.facts if f.test == "Potassium")
    assert potassium.abnormal_flag is None
    assert potassium.value == "4.1"  # every other field on the row survives
    assert "XX" in potassium.citation.quote_or_value


# ---------------------------------------------------------------------------
# 9. doc_type="intake_form" (P3.2) -- shares attach_and_extract's one code
#    path with lab_pdf; only the extraction schema/prompt/assembly differ.
# ---------------------------------------------------------------------------

# Mirrors scripts/generate_intake_form_fixture.py's page content exactly --
# the scripted double stands in for what a real VLM reading these page
# images would report, including the one deliberately unreadable field
# (page 1's DOB, covered by an opaque box in the fixture).
_INTAKE_PAGE_1_EXTRACTION = IntakeFormExtraction(
    demographics={"name": "Test Patient", "dob": None, "sex": "F", "mrn": "TEST-000000"},
    chief_concern="Intermittent chest tightness for the past 3 days.",
    medications=[],
    allergies=[],
    family_history=[],
)
_INTAKE_PAGE_2_EXTRACTION = IntakeFormExtraction(
    demographics={},
    chief_concern=None,
    medications=["Lisinopril 10mg daily", "Metformin 500mg twice daily", "Atorvastatin 20mg nightly"],
    allergies=["Penicillin", "Shellfish"],
    family_history=["Father: hypertension", "Mother: type 2 diabetes"],
)


@pytest.fixture
def fake_intake_vlm() -> _FakeVlmOllama:
    return _FakeVlmOllama([_INTAKE_PAGE_1_EXTRACTION, _INTAKE_PAGE_2_EXTRACTION])


def test_attach_and_extract_intake_form_returns_schema_valid_facts_with_citations(fake_intake_vlm, store):
    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=fake_intake_vlm, document_store=store, fact_store=store
    )

    assert isinstance(result, IngestionResult)
    assert len(result.facts) == 2  # one fact per page (each page had legible content)
    for fact in result.facts:
        assert isinstance(fact, IntakeFormFact)
        assert fact.citation.source_type == "intake_form"
        assert fact.citation.source_id == result.source_id


def test_attach_and_extract_intake_form_citations_carry_the_correct_page_number(fake_intake_vlm, store):
    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=fake_intake_vlm, document_store=store, fact_store=store
    )

    demographics_fact = next(f for f in result.facts if f.demographics)
    medications_fact = next(f for f in result.facts if f.medications)
    assert demographics_fact.citation.page_or_section == "page 1"
    assert medications_fact.citation.page_or_section == "page 2"


def test_attach_and_extract_intake_form_calls_vlm_once_per_page_with_that_pages_image(fake_intake_vlm, store):
    attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=fake_intake_vlm, document_store=store, fact_store=store
    )

    assert len(fake_intake_vlm.extract_calls) == 2
    for _messages, schema, images in fake_intake_vlm.extract_calls:
        assert schema is IntakeFormExtraction
        assert images is not None
        assert len(images) == 1


def test_intake_form_redacted_field_yields_none_not_a_guessed_value(fake_intake_vlm, store):
    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=fake_intake_vlm, document_store=store, fact_store=store
    )

    demographics_fact = next(f for f in result.facts if f.demographics)
    assert demographics_fact.demographics["dob"] is None
    # Every other demographic field on the same page was legible and is NOT
    # None -- proves the None is specific to the redacted field.
    assert demographics_fact.demographics["name"] == "Test Patient"
    assert demographics_fact.demographics["sex"] == "F"


def test_intake_form_redacted_field_citation_quote_does_not_claim_a_dob():
    from app.ingestion import _to_intake_form_facts

    facts = _to_intake_form_facts(_INTAKE_PAGE_1_EXTRACTION, source_id="src-1", page_index=0)

    assert len(facts) == 1
    quote = facts[0].citation.quote_or_value
    # The citation quotes the legible demographics/chief_concern truthfully,
    # never a fabricated DOB for the redacted field...
    assert "1990" not in quote
    # ...but it MUST truthfully carry what actually was legible on the page --
    # a citation that quoted nothing would be just as dishonest as one that
    # fabricated the DOB.
    assert "Test Patient" in quote
    assert "sex=F" in quote


def test_intake_form_empty_string_fields_normalize_to_not_found(store):
    """An empty/whitespace-only string is not legible data -- the VLM (or a
    scripted double standing in for it) reporting "" for a field must be
    treated the same as reporting None/omitting it entirely, never stored
    or quoted as if something was actually read."""
    blank_page = IntakeFormExtraction(
        demographics={"name": "Test Patient", "dob": "   "},
        chief_concern="",
        medications=["Lisinopril 10mg daily", "", "   "],
        allergies=[""],
        family_history=["Father: hypertension", ""],
    )
    empty_page = IntakeFormExtraction(
        demographics={}, chief_concern=None, medications=[], allergies=[], family_history=[]
    )
    vlm = _FakeVlmOllama([blank_page, empty_page])

    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=vlm, document_store=store, fact_store=store
    )

    assert len(result.facts) == 1  # page 2 had nothing legible even before normalization
    fact = result.facts[0]
    assert fact.chief_concern is None
    assert fact.demographics["dob"] is None
    assert fact.demographics["name"] == "Test Patient"
    assert fact.medications == ["Lisinopril 10mg daily"]
    assert fact.allergies == []  # the sole entry was blank -- filtered, not stored as ""
    assert fact.family_history == ["Father: hypertension"]

    quote = fact.citation.quote_or_value
    assert "chief_concern:" not in quote  # no section for a field that normalized to None
    assert "allergies:" not in quote  # no section for a list that normalized to empty
    for segment in quote.split("; "):
        assert segment.strip() != ""  # no empty list items/sections leaked into the quote


def test_intake_form_all_pages_failing_yields_no_facts_and_marks_every_page_failed(store):
    failing_vlm = _FakeVlmOllama(error=True)

    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=failing_vlm, document_store=store, fact_store=store
    )

    assert result.facts == []
    assert result.failed_pages == [1, 2]
    assert result.pages_total == 2


def test_intake_form_mixed_outcome_keeps_succeeded_page_facts_and_marks_only_the_failed_page(store):
    class _MixedVlm:
        """Page 1 succeeds, page 2 fails outright."""

        def __init__(self) -> None:
            self.calls = 0

        def extract(self, prompt_or_messages: Any, schema: type, *, options: Any = None, images: list[str] | None = None) -> Any:
            self.calls += 1
            if self.calls == 1:
                return _INTAKE_PAGE_1_EXTRACTION
            raise OllamaError("scripted failure on page 2")

    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=_MixedVlm(), document_store=store, fact_store=store
    )

    assert len(result.facts) == 1
    assert result.facts[0].citation.page_or_section == "page 1"
    assert result.failed_pages == [2]
    assert result.pages_total == 2


def test_intake_form_page_with_nothing_legible_yields_no_fact_for_that_page(store):
    empty_extraction = IntakeFormExtraction(
        demographics={}, chief_concern=None, medications=[], allergies=[], family_history=[]
    )
    vlm = _FakeVlmOllama([_INTAKE_PAGE_1_EXTRACTION, empty_extraction])

    result = attach_and_extract(
        1, _INTAKE_FIXTURE_PATH, "intake_form", ollama_client=vlm, document_store=store, fact_store=store
    )

    # Page 2 legitimately had nothing legible -- no fact fabricated for it --
    # but it is NOT in failed_pages (the VLM call succeeded; it just read an
    # empty page), distinct from an outright extraction failure.
    assert len(result.facts) == 1
    assert result.failed_pages == []
    assert result.pages_total == 2


# ---------------------------------------------------------------------------
# 9. P3.9a: patient-scoped fact lookup (LocalIngestionStore.list_citations_for_patient)
#
# Backs /chat's per-patient lab/intake-form DocumentCitation path (issue #46):
# a live turn needs to look up ONE patient's own extracted-fact citations,
# scoped strictly by patient_id, to build a app.verification.DocumentFactIndex
# from them. The critical property under test is patient isolation -- a
# lookup for patient A must NEVER return a citation stored under patient B,
# regardless of how many documents either patient has ingested.
# ---------------------------------------------------------------------------


def test_list_citations_for_patient_returns_only_that_patients_citations(store, fake_vlm):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    citations = store.list_citations_for_patient(1)

    assert len(citations) == 8
    assert all(citation.source_type == "lab_pdf" for citation in citations)
    assert all(citation.source_id == result.source_id for citation in citations)
    assert any("Hemoglobin A1c" in citation.quote_or_value for citation in citations)


def test_list_citations_for_patient_never_returns_a_different_patients_citations(store):
    """The load-bearing security case (issue #46): patient A's /chat turn must
    never see patient B's extracted facts. Two patients each ingest their own
    lab report into the SAME store; a lookup for one must return only that
    one's citations, never the other's."""
    vlm_a = _FakeVlmOllama([LabPageExtraction(rows=_PAGE_1_ROWS), LabPageExtraction(rows=_PAGE_2_ROWS)])
    vlm_b = _FakeVlmOllama([LabPageExtraction(rows=_PAGE_1_ROWS), LabPageExtraction(rows=_PAGE_2_ROWS)])

    result_a = attach_and_extract(101, _FIXTURE_PATH, "lab_pdf", ollama_client=vlm_a, document_store=store, fact_store=store)
    result_b = attach_and_extract(202, _FIXTURE_PATH, "lab_pdf", ollama_client=vlm_b, document_store=store, fact_store=store)

    citations_a = store.list_citations_for_patient(101)
    citations_b = store.list_citations_for_patient(202)

    source_ids_a = {citation.source_id for citation in citations_a}
    source_ids_b = {citation.source_id for citation in citations_b}

    assert source_ids_a == {result_a.source_id}
    assert source_ids_b == {result_b.source_id}
    # No cross-contamination in either direction.
    assert source_ids_a.isdisjoint(source_ids_b)
    assert result_b.source_id not in source_ids_a
    assert result_a.source_id not in source_ids_b


def test_list_citations_for_patient_with_no_ingested_documents_returns_empty(store):
    assert store.list_citations_for_patient(999) == []


def test_list_citations_for_patient_requires_a_type_strict_int_match(tmp_path: Path):
    """Defense-in-depth: a sidecar whose stored ``patient_id`` is a float
    (e.g. ``101.0`` from some future ingestion path) must NOT match the int
    ``101`` via Python numeric equality -- the compare is type-strict, so a
    non-int stored id can never coincide with a different patient's id."""
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")
    facts_dir = tmp_path / "ingestion" / "facts"
    citation = {
        "source_type": "lab_pdf",
        "source_id": "deadbeef" * 4,
        "page_or_section": "page 1",
        "field_or_chunk_id": "Hemoglobin A1c#page1-row0",
        "quote_or_value": "Hemoglobin A1c: 5.4",
    }
    (facts_dir / "float_pid.json").write_text(
        json.dumps({"patient_id": 101.0, "source_id": "deadbeef" * 4, "facts": [{"citation": citation}]})
    )

    assert store.list_citations_for_patient(101) == []
