"""Hermetic tests for ``app.ingestion`` (P3.1 document ingestion, first
slice: ``doc_type="lab_pdf"``).

Everything here is hermetic: the VLM is a scripted double
(``_FakeVlmOllama``), never a real Ollama call -- mirrors
``tests/test_extraction.py``'s ``_FakeExtractOllama`` pattern. PDF
rendering itself IS real (``pypdfium2`` over the committed fixture,
``tests/fixtures/lab_report_synthetic.pdf``, generated by
``scripts/generate_lab_pdf_fixture.py``) -- it is fast, deterministic, and
needs no model or network.

Pins two contracts:
  1. ``attach_and_extract`` returns schema-valid ``LabResultFact`` objects,
     each carrying a ``Citation`` back to its source page.
  2. The no-fabrication rule: a field the (scripted, standing in for the
     real) VLM could not read comes back ``None``, never a guessed value --
     exercised via the fixture's deliberately redacted field (Creatinine's
     collection date on page 2).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from app.ingestion import (
    ExtractedLabRow,
    IngestionResult,
    LabPageExtraction,
    LocalIngestionStore,
    attach_and_extract,
    render_pdf_pages_to_png,
)
from app.ollama_client import OllamaError
from app.schemas.ingestion import LabResultFact

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "lab_report_synthetic.pdf"

# Mirrors scripts/generate_lab_pdf_fixture.py's page content exactly -- the
# scripted double stands in for what a real VLM reading these page images
# would report, including the one deliberately unreadable field (page 2's
# Creatinine collection_date, covered by an opaque box in the fixture).
_PAGE_1_ROWS = [
    ExtractedLabRow(test="Hemoglobin A1c", value="5.4", unit="%", reference_range="4.0-5.6", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="Fasting Glucose", value="142", unit="mg/dL", reference_range="70-99", collection_date="2026-06-01", abnormal_flag="H"),
    ExtractedLabRow(test="Total Cholesterol", value="188", unit="mg/dL", reference_range="<200", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="LDL Cholesterol", value="112", unit="mg/dL", reference_range="<100", collection_date="2026-06-01", abnormal_flag="H"),
]
_PAGE_2_ROWS = [
    ExtractedLabRow(test="HDL Cholesterol", value="58", unit="mg/dL", reference_range="40-60", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="Triglycerides", value="97", unit="mg/dL", reference_range="<150", collection_date="2026-06-01", abnormal_flag="N"),
    ExtractedLabRow(test="TSH", value="2.1", unit="mIU/L", reference_range="0.4-4.0", collection_date="2026-06-01", abnormal_flag="N"),
    # The deliberately unreadable field: collection_date is None, never guessed.
    ExtractedLabRow(test="Creatinine", value="0.9", unit="mg/dL", reference_range="0.6-1.3", collection_date=None, abnormal_flag="N"),
]


class _FakeVlmOllama:
    """Scripted VLM extraction double: returns one canned ``LabPageExtraction``
    per call, in order (or raises), and records what it was called with."""

    def __init__(self, results: list[LabPageExtraction] | None = None, *, error: bool = False) -> None:
        self._results = results or []
        self._error = error
        self.extract_calls: list[tuple[list[dict[str, Any]], type, list[str] | None]] = []

    def extract(
        self, prompt_or_messages: Any, schema: type, *, options: Any = None, images: list[str] | None = None
    ) -> Any:
        self.extract_calls.append((prompt_or_messages, schema, images))
        if self._error:
            raise OllamaError("scripted VLM extraction failure")
        return self._results[len(self.extract_calls) - 1]


@pytest.fixture
def fake_vlm() -> _FakeVlmOllama:
    return _FakeVlmOllama([LabPageExtraction(rows=_PAGE_1_ROWS), LabPageExtraction(rows=_PAGE_2_ROWS)])


@pytest.fixture
def store(tmp_path: Path) -> LocalIngestionStore:
    return LocalIngestionStore(base_dir=tmp_path / "ingestion")


# ---------------------------------------------------------------------------
# 1. PDF page rendering (real pypdfium2, no model call)
# ---------------------------------------------------------------------------


def test_render_pdf_pages_to_png_returns_one_image_per_page():
    pages = render_pdf_pages_to_png(_FIXTURE_PATH)

    assert len(pages) == 2
    for page_png in pages:
        assert page_png.startswith(b"\x89PNG\r\n\x1a\n")  # PNG magic bytes


# ---------------------------------------------------------------------------
# 2. attach_and_extract: schema-valid facts + citations
# ---------------------------------------------------------------------------


def test_attach_and_extract_returns_schema_valid_facts_with_citations(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    assert isinstance(result, IngestionResult)
    assert len(result.facts) == 8  # 4 rows/page x 2 pages
    for fact in result.facts:
        assert isinstance(fact, LabResultFact)
        assert fact.citation.source_type == "lab_pdf"
        assert fact.citation.source_id == result.source_id


def test_attach_and_extract_citations_carry_the_correct_page_number(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    page_1_facts = [f for f in result.facts if f.test == "Hemoglobin A1c"]
    page_2_facts = [f for f in result.facts if f.test == "HDL Cholesterol"]
    assert page_1_facts[0].citation.page_or_section == "page 1"
    assert page_2_facts[0].citation.page_or_section == "page 2"


def test_attach_and_extract_calls_vlm_once_per_page_with_that_pages_image(fake_vlm, store):
    attach_and_extract(1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store)

    assert len(fake_vlm.extract_calls) == 2
    for _messages, schema, images in fake_vlm.extract_calls:
        assert schema is LabPageExtraction
        assert images is not None
        assert len(images) == 1  # one image (this page) per call


def test_attach_and_extract_rejects_unsupported_doc_type(fake_vlm, store):
    with pytest.raises(ValueError, match="lab_pdf"):
        attach_and_extract(
            1, _FIXTURE_PATH, "intake_form", ollama_client=fake_vlm, document_store=store, fact_store=store  # type: ignore[arg-type]
        )


# ---------------------------------------------------------------------------
# 3. No-fabrication: the deliberately unreadable field never gets a guess
# ---------------------------------------------------------------------------


def test_unreadable_field_yields_none_not_a_guessed_value(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    creatinine = next(f for f in result.facts if f.test == "Creatinine")
    assert creatinine.collection_date is None
    # Every other field on the same row was legible and is NOT None -- proves
    # the None is specific to the unreadable field, not a whole-row failure.
    assert creatinine.value == "0.9"
    assert creatinine.unit == "mg/dL"


def test_unreadable_field_citation_quote_reflects_not_found(fake_vlm, store):
    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    creatinine = next(f for f in result.facts if f.test == "Creatinine")
    # The citation's quote is for the row's headline value (legible: "0.9"),
    # not the missing collection_date -- it must never claim a date was read.
    assert "0.9" in creatinine.citation.quote_or_value
    assert "2026" not in creatinine.citation.quote_or_value


def test_all_none_row_citation_quote_says_not_found():
    from app.ingestion import _quote_for_row

    row = ExtractedLabRow(test="Illegible Test", value=None, unit=None, reference_range=None, collection_date=None, abnormal_flag=None)
    assert _quote_for_row(row) == "Illegible Test: (not found)"


def test_extraction_failure_yields_no_facts_for_that_page_not_a_guess(store):
    failing_vlm = _FakeVlmOllama(error=True)

    result = attach_and_extract(
        1, _FIXTURE_PATH, "lab_pdf", ollama_client=failing_vlm, document_store=store, fact_store=store
    )

    # Fails soft, but to EMPTY -- never fabricates rows for a page the VLM
    # couldn't process at all.
    assert result.facts == []


# ---------------------------------------------------------------------------
# 4. LocalIngestionStore (P3.1's disclosed local-disk storage placeholder)
# ---------------------------------------------------------------------------


def test_local_store_persists_the_source_document_bytes(tmp_path: Path):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")

    source_id = store.save_source_document(1, "lab_pdf", _FIXTURE_PATH)

    saved = tmp_path / "ingestion" / "documents" / f"{source_id}.pdf"
    assert saved.read_bytes() == _FIXTURE_PATH.read_bytes()


def test_local_store_persists_facts_as_json(tmp_path: Path, fake_vlm):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")

    result = attach_and_extract(
        42, _FIXTURE_PATH, "lab_pdf", ollama_client=fake_vlm, document_store=store, fact_store=store
    )

    saved = tmp_path / "ingestion" / "facts" / f"{result.source_id}.json"
    payload = json.loads(saved.read_text())
    assert payload["patient_id"] == 42
    assert payload["source_id"] == result.source_id
    assert len(payload["facts"]) == 8
    assert payload["facts"][0]["citation"]["source_type"] == "lab_pdf"


def test_local_store_generates_distinct_source_ids(tmp_path: Path):
    store = LocalIngestionStore(base_dir=tmp_path / "ingestion")

    first = store.save_source_document(1, "lab_pdf", _FIXTURE_PATH)
    second = store.save_source_document(1, "lab_pdf", _FIXTURE_PATH)

    assert first != second
