x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mysql.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mysql:8.4.10@sha256:c831a0f11348d402b43d77453e17d770be2eef356615a2823fe0f5a0d6c8b9af
  openemr:
    image: openemr/openemr:flex-3.23-php-8.5@sha256:1d2c8345a320cf2985c9d02138951267739ec498559ca724b3d5397e4568482e
