#!/usr/bin/env bash
# Regenerates services/copilot-agent/requirements.txt (board issue 213).
#
# Runs pip-compile INSIDE the exact digest-pinned base image the Dockerfile
# installs into (python:3.11-slim@sha256:...), so the hashes and pins this
# script produces are for the platform/Python build that actually ships --
# not whatever happens to be on the host running this script. Locks only
# [project.dependencies] (the production runtime closure) -- the `dev`
# extra stays floor/ceiling-only per #196, since it's never installed in
# the built image.
set -euo pipefail

# Keep in lockstep with the Dockerfile's FROM line -- both must reference
# the same image so the lock is generated against the identical Python
# build/platform the container actually ships.
BASE_IMAGE="python:3.11-slim@sha256:baf89808ec37adeaab83cec287adb4a2afa4a11c1d51e961c7ec737877e61af6"
# Pinned so a pip-tools release doesn't silently change hash/pin output
# between runs of this script.
PIP_TOOLS_VERSION="7.5.0"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
agent_dir="${script_dir}/../services/copilot-agent"

# MSYS_NO_PATHCONV avoids Git Bash on Windows mangling the absolute
# container-side mount path (e.g. "/work") into a host path.
MSYS_NO_PATHCONV=1 docker run --rm \
    -v "${agent_dir}:/work" \
    -w /work \
    "${BASE_IMAGE}" \
    bash -c "
        set -euo pipefail
        pip install --no-cache-dir 'pip-tools==${PIP_TOOLS_VERSION}'
        pip-compile pyproject.toml \
            -o requirements.txt \
            --generate-hashes \
            --allow-unsafe \
            --strip-extras \
            --no-header
        {
            echo '# Generated by scripts/lock-deps.sh -- DO NOT EDIT BY HAND.'
            echo '# Regenerate with: bash scripts/lock-deps.sh'
            echo '#'
            echo '# Pins the exact production runtime dependency closure (transitives'
            echo '# included) that services/copilot-agent/Dockerfile installs with'
            echo '# \`pip install --require-hashes\`. pyproject.toml'\''s [project.dependencies]'
            echo '# ranges remain the human-facing contract this lock must stay inside'
            echo '# (see tests/test_dependency_lock.py).'
            echo
            cat requirements.txt
        } > requirements.txt.tmp
        mv requirements.txt.tmp requirements.txt
    "

echo "Wrote ${agent_dir}/requirements.txt"
